import { Link } from "react-router-dom";
import { useEffect, useState } from "react";
import { Boxes, IndianRupee, ShoppingBag, Users } from "lucide-react";
import api from "../utils/api";

const money = value => `₹${Number(value || 0).toLocaleString("en-IN")}`;
function useFetch(path) { const [data, setData] = useState(null), [error, setError] = useState(""); useEffect(() => { api.get(path).then(r => setData(r.data)).catch(e => setError(e.response?.data?.error || "Unable to load data.")); }, [path]); return { data, error, setData }; }
export function AdminDashboard() { const { data, error } = useFetch("/admin/dashboard"); if (error) return <p className="text-red-600">{error}</p>; if (!data) return <p>Loading dashboard...</p>; const cards = [{ label: "Total Revenue", value: money(data.totalRevenue), icon: IndianRupee }, { label: "Total Orders", value: data.totalOrders, icon: ShoppingBag }, { label: "Total Books", value: data.totalBooks, icon: Boxes }, { label: "Total Users", value: data.totalUsers, icon: Users }, { label: "Pending Orders", value: data.pendingOrders, icon: ShoppingBag }, { label: "Confirmed", value: data.confirmedOrders, icon: ShoppingBag }, { label: "Shipped", value: data.shippedOrders, icon: ShoppingBag }, { label: "Delivered", value: data.deliveredOrders, icon: ShoppingBag }, { label: "Cancelled", value: data.cancelledOrders, icon: ShoppingBag }]; return <section><div className="grid gap-4 md:grid-cols-3 xl:grid-cols-5">{cards.map(card => { const Icon=card.icon; return <div key={card.label} className="surface p-5"><Icon className="text-brand-600"/><p className="mt-4 text-sm text-slate-500">{card.label}</p><p className="text-2xl font-black">{card.value}</p></div>; })}</div><section className="surface mt-6 overflow-hidden"><div className="p-5"><h2 className="text-xl font-black">Recent Orders</h2></div><OrdersTable orders={data.recentOrders} /></section></section>; }
export function AdminProducts() { const { data: books, error, setData } = useFetch("/books"); const remove = async id => { if (!window.confirm("Delete this book?")) return; await api.delete(`/books/${id}`); setData(books.filter(book => book.id !== id)); }; const edit = async book => { const name = window.prompt("Title", book.name); if (name === null) return; const author = window.prompt("Author", book.author); const category = window.prompt("Category", book.category || ""); const price = window.prompt("Price", book.price); const quantity = window.prompt("Stock", book.quantity); const description = window.prompt("Description", book.description || ""); try { await api.put(`/books/${book.id}`, { ...book, name, author, category, price: Number(price), quantity: Number(quantity), description }); setData(books.map(item => item.id === book.id ? { ...book, name, author, category, price: Number(price), quantity: Number(quantity), description } : item)); } catch (e) { alert(e.response?.data?.error || "Unable to update book."); } }; return <section className="surface overflow-hidden"><div className="flex items-center justify-between border-b p-5 dark:border-slate-800"><h1 className="text-xl font-black">Book Management</h1><Link to="/add-product" className="btn-primary py-2">Add Book</Link></div>{error ? <p className="p-5 text-red-600">{error}</p> : !books ? <p className="p-5">Loading books...</p> : <Table headers={["Book", "Category", "Author", "Price", "Stock", "Actions"]} rows={books.map(book => [book.name, book.category || "—", book.author, money(book.price), book.quantity, <span className="space-x-3"><button onClick={() => edit(book)} className="text-brand-600">Edit</button><button onClick={() => remove(book.id)} className="text-red-600">Delete</button></span>])} />}</section>; }
export function AdminUsers() { const { data, error } = useFetch("/admin/users"); return <section className="surface overflow-hidden"><div className="border-b p-5 dark:border-slate-800"><h1 className="text-xl font-black">User Management</h1></div>{error ? <p className="p-5 text-red-600">{error}</p> : !data ? <p className="p-5">Loading users...</p> : <Table headers={["Name", "Email", "Phone", "Role"]} rows={data.map(user => [user.name, user.email || "—", user.phoneNumber || "—", user.role])} empty="No users found." />}</section>; }
export function AdminOrders() { const { data, error, setData } = useFetch("/admin/orders"); const update = async (id, status) => { try { const response = await api.patch(`/admin/orders/${id}/status`, { status }); setData(data.map(order => order.id === id ? response.data : order)); } catch (e) { alert(e.response?.data?.error || "Unable to update order."); } }; return <section className="surface overflow-hidden"><div className="border-b p-5 dark:border-slate-800"><h1 className="text-xl font-black">Order Management</h1></div>{error ? <p className="p-5 text-red-600">{error}</p> : !data ? <p className="p-5">Loading orders...</p> : <OrdersTable orders={data} update={update} />}</section>; }
export function AdminAnalytics() { return <section className="surface p-6"><h1 className="text-xl font-black">Analytics</h1><p className="mt-2 text-slate-500">Live order and revenue totals are available on the dashboard.</p><Link to="/admin" className="btn-primary mt-6">View Dashboard</Link></section>; }
function OrdersTable({ orders, update }) { return <Table headers={["Order ID", "Customer", "Date", "Amount", "Status"]} rows={orders.map(order => [`#${order.id}`, order.customer.name, new Date(order.orderDate).toLocaleDateString(), money(order.totalAmount), update ? <select className="input py-1" value={order.status} onChange={e => update(order.id, e.target.value)}>{["PENDING", "CONFIRMED", "SHIPPED", "DELIVERED", "CANCELLED"].map(status => <option key={status}>{status}</option>)}</select> : order.status])} empty="No recent orders" />; }
function Table({ headers, rows, empty = "No data found." }) { return <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-slate-500 dark:bg-slate-900 dark:text-slate-400"><tr>{headers.map(header => <th key={header} className="px-5 py-4 font-bold">{header}</th>)}</tr></thead><tbody className="divide-y divide-slate-100 dark:divide-slate-800">{rows.length ? rows.map((row, index) => <tr key={index}>{row.map((cell, i) => <td key={i} className="px-5 py-4 font-semibold">{cell}</td>)}</tr>) : <tr><td colSpan={headers.length} className="px-5 py-6 text-slate-500">{empty}</td></tr>}</tbody></table></div>; }
